# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='expires',
        ),
        migrations.AddField(
            model_name='session',
            name='creation_age',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='max_age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
