# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 22:05
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('general', '0001_initial'), ('general', '0002_user_user_creds')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
                ('length', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('cast_list', models.CharField(max_length=1000)),
                ('datetime', models.DateTimeField()),
                ('movie_poster', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
                ('movies', models.ManyToManyField(related_name='available_movies', to='general.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('favourite_movies', models.ManyToManyField(related_name='favourite_movies', to='general.Movie')),
                ('movie_wishlist', models.ManyToManyField(related_name='movie_wishlist', to='general.Movie')),
                ('user_creds', models.Field(null=True, verbose_name=django.contrib.auth.models.User)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Movie'),
        ),
        migrations.AddField(
            model_name='event',
            name='theatre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Theatre'),
        ),
        migrations.AddField(
            model_name='event',
            name='users',
            field=models.ManyToManyField(related_name='event_users', to='general.User'),
        ),
    ]
