# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('general', '0002_user_user_creds'), ('general', '0003_auto_20171006_1752')]

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=100),
            preserve_default=False,
        ),
    ]
