# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 21:35
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_creds',
            field=models.Field(null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
