# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_user_user_creds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_creds',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=100),
            preserve_default=False,
        ),
    ]
