# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20171006_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='event',
            name='theatre',
        ),
        migrations.RemoveField(
            model_name='event',
            name='users',
        ),
        migrations.RemoveField(
            model_name='theatre',
            name='movies',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favourite_movies',
        ),
        migrations.RemoveField(
            model_name='user',
            name='movie_wishlist',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Theatre',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
