# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_auto_20171006_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='user_creds',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
