# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_movie_user_creds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='user_creds',
        ),
        migrations.AddField(
            model_name='user',
            name='user_creds',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
