# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_auto_20171006_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_creds',
        ),
    ]
