# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_remove_user_user_creds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favourite_movies',
            field=models.ManyToManyField(null=True, related_name='favourite_movies', to='general.Movie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='movie_wishlist',
            field=models.ManyToManyField(null=True, related_name='movie_wishlist', to='general.Movie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
